### DISCUSSION TITLE
Build succeeds but 404

### DISCUSSION THREAD

**Discussion by zklegal** [rossjrw/pr-preview-action#106] [Q&A]
I receive a 404 error when visiting the generated url.

- My gh-pages branch serves the github pages site
- My workflow successfully runs and the directory is created with build files in my gh-pages branch but when I visit <github-pages-url>.com/<path>/pr-preview/pr-2/ I get a 404
- In my gh-pages branch there is both a ./<path>/pr-preview/pr-2 folder as well as a pr-preview/pr-2

I'm not sure why I am getting a 404

```yml
name: Deploy PR previews
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    
concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install and Build
        if: github.event.action != 'closed'
        run: |
          npm install
          npm run build
          
      - name: List build output
        if: github.event.action != 'closed'
        run: |
          echo "Build directory contents:"
          ls -la ./dist/
          
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
          umbrella-dir: pr-preview
          preview-branch: gh-pages
```
