### DISCUSSION TITLE
Error: Resource not accessible by integration

### DISCUSSION THREAD

**Discussion by FreaxMATE** [rossjrw/pr-preview-action#75] [Q&A] [answered]
I get the error in https://github.com/rossjrw/pr-preview-action/discussions/68 and https://github.com/rossjrw/pr-preview-action/discussions/59 however on a PR from the same repository and without pushing to a different repository.
My action:
``` yaml
# .github/workflows/preview.yml
name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Install dependencies
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material ipykernel nbconvert traitlets jupytext pandas python-markdown-math mkdocs-simple-hooks pillow cairosvg matplotlib scipy plotly ipywidgets
      - name: Build site
      - run: mkdocs build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
```

and this deployment: https://github.com/Hephaestus-Energy-Forge/Hephaestus-Energy-Forge/actions/runs/7597038400/job/20691926420
