### DISCUSSION TITLE
Cleanup is not happening as it should on PR close

### DISCUSSION THREAD

**Discussion by xaviergmail** [rossjrw/pr-preview-action#77] [Q&A] [answered]
We currently have 200+ orphaned directories under our PR previews. The action runs, but nothing is being deleted. Here is the output:

```

Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config --global --add safe.directory /home/runner/work/vision-web/vision-web
/usr/bin/git config user.name xaviergmail
/usr/bin/git config user.email xaviergmail@users.noreply.github.com
/usr/bin/git config core.ignorecase false
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/<redacted>
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/<redacted>.git refs/heads/gh-pages
6460bcf9c7b548bce1544e269a8ee0d4e21cc652	refs/heads/gh-pages
Creating worktree…
/usr/bin/git fetch --no-recurse-submodules --depth=1 origin gh-pages
From https://github.com/<redacted>
  * branch            gh-pages   -> FETCH_HEAD
 * [new branch]      gh-pages   -> origin/gh-pages
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD ef1ddab)
/usr/bin/git checkout -B gh-pages origin/gh-pages
Previous HEAD position was ef1ddab Merge 47a6e8a6cdf30c80c317f0b6d0896a4b8be0995f into cb1eea009e14ea6d3f882c373f2094c4f144a4df
Switched to a new branch 'gh-pages'
branch 'gh-pages' set up to track 'origin/gh-pages'.
/usr/bin/chmod -R +rw /tmp/tmp.MoYqQjkDJm
Creating target folder if it doesn't already exist… 📌
/usr/bin/rsync -q -av --checksum --progress /tmp/tmp.MoYqQjkDJm/. github-pages-deploy-action-temp-deployment-folder/pr-previews/pr-1923 --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github
Checking if there are files to commit…
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/z4xrvq1b2
Switched to a new branch 'github-pages-deploy-action/z4xrvq1b2'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
There is nothing to commit. Exiting early… 📭
```

**Comment by rossjrw** [comment]
Moved to Discussion as this is a question about a setup issue rather than a problem with the action itself. (If a problem with the action is discovered as part of this discussion then create an issue for that.)

@xaviergmail I'm assuming this is from a private repository; regardless, this isn't enough information for me to work out what's happening here. With your repo's anonymity in mind, could you please share:

1. A summary of the contents of the orphaned dirs (e.g. if it's just a few leftover files, or if it's the entire preview and if so roughly how many files that is)
2. Your entire workflow file, anonymised, including this action's step as verbatim as possible, and including other steps in enough detail to know roughly what they're doing
3. Environment logs for the deploy part of the above action workflow logs (anonymised) - which for reference is in a collapsible section and looks like this:

<img src="https://github.com/rossjrw/pr-preview-action/assets/29130152/e7d9e23c-d6c3-4855-a6ae-5e12221649bf" width="435">

**Reply by xaviergmail** [reply]
Thanks for the swift reply!

<details>
<summary><h2>Orphaned file count</h2></summary>

```
xavier@Xaviers-M2 /V/p/**********-gh-pages (gh-pages)> for dir in pr-preview/*/
                                                               set dir_name (basename $dir)
                                                               set file_count (find $dir -type f | wc -l)
                                                               echo "./pr-review/$dir_name: $file_count" files
                                                       end
./pr-review/pr-1700: 72 files
./pr-review/pr-1701: 72 files
./pr-review/pr-1702: 72 files
./pr-review/pr-1704: 72 files
./pr-review/pr-1705: 72 files
./pr-review/pr-1707: 72 files
./pr-review/pr-1708: 72 files
./pr-review/pr-1711: 72 files
./pr-review/pr-1712: 72 files
./pr-review/pr-1713: 72 files
./pr-review/pr-1714: 72 files
./pr-review/pr-1715: 72 files
./pr-review/pr-1716: 72 files
./pr-review/pr-1717: 72 files
./pr-review/pr-1718: 72 files
./pr-review/pr-1719: 72 files
./pr-review/pr-1720: 72 files
./pr-review/pr-1721: 72 files
./pr-review/pr-1722: 72 files
./pr-review/pr-1723: 72 files
./pr-review/pr-1724: 72 files
./pr-review/pr-1725: 72 files
./pr-review/pr-1726: 72 files
./pr-review/pr-1727: 73 files
./pr-review/pr-1728: 72 files
./pr-review/pr-1730: 72 files
./pr-review/pr-1731: 75 files
./pr-review/pr-1734: 73 files
./pr-review/pr-1735: 73 files
./pr-review/pr-1736: 76 files
./pr-review/pr-1739: 78 files
./pr-review/pr-1741: 78 files
./pr-review/pr-1742: 78 files
./pr-review/pr-1743: 78 files
./pr-review/pr-1744: 78 files
./pr-review/pr-1745: 80 files
./pr-review/pr-1746: 72 files
./pr-review/pr-1747: 72 files
./pr-review/pr-1748: 72 files
./pr-review/pr-1749: 72 files
./pr-review/pr-1750: 72 files
./pr-review/pr-1752: 72 files
./pr-review/pr-1753: 72 files
./pr-review/pr-1754: 72 files
./pr-review/pr-1755: 72 files
./pr-review/pr-1756: 72 files
./pr-review/pr-1757: 72 files
./pr-review/pr-1758: 72 files
./pr-review/pr-1759: 72 files
./pr-review/pr-1760: 72 files
./pr-review/pr-1761: 72 files
./pr-review/pr-1762: 72 files
./pr-review/pr-1763: 72 files
./pr-review/pr-1764: 72 files
./pr-review/pr-1765: 72 files
./pr-review/pr-1766: 72 files
./pr-review/pr-1767: 74 files
./pr-review/pr-1768: 74 files
./pr-review/pr-1769: 74 files
./pr-review/pr-1770: 74 files
./pr-review/pr-1771: 74 files
./pr-review/pr-1772: 74 files
./pr-review/pr-1773: 74 files
./pr-review/pr-1774: 74 files
./pr-review/pr-1775: 74 files
./pr-review/pr-1777: 74 files
./pr-review/pr-1779: 74 files
./pr-review/pr-1780: 74 files
./pr-review/pr-1781: 74 files
./pr-review/pr-1782: 74 files
./pr-review/pr-1783: 74 files
./pr-review/pr-1785: 74 files
./pr-review/pr-1786: 74 files
./pr-review/pr-1787: 74 files
./pr-review/pr-1788: 74 files
./pr-review/pr-1789: 74 files
./pr-review/pr-1791: 74 files
./pr-review/pr-1792: 74 files
./pr-review/pr-1793: 74 files
./pr-review/pr-1794: 74 files
./pr-review/pr-1795: 74 files
./pr-review/pr-1796: 74 files
./pr-review/pr-1797: 74 files
./pr-review/pr-1798: 74 files
./pr-review/pr-1799: 74 files
./pr-review/pr-1800: 74 files
./pr-review/pr-1802: 74 files
./pr-review/pr-1803: 74 files
./pr-review/pr-1804: 74 files
./pr-review/pr-1805: 74 files
./pr-review/pr-1806: 74 files
./pr-review/pr-1807: 74 files
./pr-review/pr-1808: 74 files
./pr-review/pr-1809: 74 files
./pr-review/pr-1810: 74 files
./pr-review/pr-1811: 74 files
./pr-review/pr-1812: 74 files
./pr-review/pr-1813: 74 files
./pr-review/pr-1814: 74 files
./pr-review/pr-1815: 74 files
./pr-review/pr-1816: 74 files
./pr-review/pr-1817: 74 files
./pr-review/pr-1818: 74 files
./pr-review/pr-1819: 74 files
./pr-review/pr-1820: 74 files
./pr-review/pr-1821: 74 files
./pr-review/pr-1822: 74 files
./pr-review/pr-1823: 74 files
./pr-review/pr-1824: 74 files
./pr-review/pr-1825: 74 files
./pr-review/pr-1826: 74 files
./pr-review/pr-1827: 74 files
./pr-review/pr-1828: 74 files
./pr-review/pr-1829: 74 files
./pr-review/pr-1830: 74 files
./pr-review/pr-1831: 74 files
./pr-review/pr-1832: 74 files
./pr-review/pr-1833: 74 files
./pr-review/pr-1834: 74 files
./pr-review/pr-1835: 74 files
./pr-review/pr-1837: 74 files
./pr-review/pr-1838: 74 files
./pr-review/pr-1839: 74 files
./pr-review/pr-1840: 74 files
./pr-review/pr-1841: 74 files
./pr-review/pr-1842: 74 files
./pr-review/pr-1843: 74 files
./pr-review/pr-1844: 74 files
./pr-review/pr-1845: 74 files
./pr-review/pr-1846: 74 files
./pr-review/pr-1847: 74 files
./pr-review/pr-1848: 74 files
./pr-review/pr-1849: 74 files
./pr-review/pr-1850: 74 files
./pr-review/pr-1851: 74 files
./pr-review/pr-1852: 74 files
./pr-review/pr-1853: 74 files
./pr-review/pr-1854: 74 files
./pr-review/pr-1855: 74 files
./pr-review/pr-1856: 74 files
./pr-review/pr-1857: 74 files
./pr-review/pr-1858: 74 files
./pr-review/pr-1859: 74 files
./pr-review/pr-1860: 74 files
./pr-review/pr-1861: 74 files
./pr-review/pr-1862: 74 files
./pr-review/pr-1863: 74 files
./pr-review/pr-1864: 74 files
./pr-review/pr-1865: 74 files
./pr-review/pr-1866: 74 files
./pr-review/pr-1867: 74 files
./pr-review/pr-1868: 74 files
./pr-review/pr-1870: 74 files
./pr-review/pr-1871: 74 files
./pr-review/pr-1872: 74 files
./pr-review/pr-1873: 74 files
./pr-review/pr-1874: 74 files
./pr-review/pr-1875: 74 files
./pr-review/pr-1876: 74 files
./pr-review/pr-1877: 74 files
./pr-review/pr-1878: 74 files
./pr-review/pr-1879: 74 files
./pr-review/pr-1880: 74 files
./pr-review/pr-1881: 74 files
./pr-review/pr-1882: 74 files
./pr-review/pr-1883: 74 files
./pr-review/pr-1884: 74 files
./pr-review/pr-1885: 74 files
./pr-review/pr-1886: 74 files
./pr-review/pr-1887: 74 files
./pr-review/pr-1888: 74 files
./pr-review/pr-1889: 74 files
./pr-review/pr-1890: 74 files
./pr-review/pr-1891: 74 files
./pr-review/pr-1892: 74 files
./pr-review/pr-1893: 74 files
./pr-review/pr-1894: 74 files
./pr-review/pr-1895: 74 files
./pr-review/pr-1896: 74 files
./pr-review/pr-1897: 74 files
./pr-review/pr-1898: 74 files
./pr-review/pr-1899: 74 files
./pr-review/pr-1900: 74 files
./pr-review/pr-1902: 74 files
./pr-review/pr-1903: 74 files
./pr-review/pr-1904: 74 files
./pr-review/pr-1905: 74 files
./pr-review/pr-1906: 74 files
./pr-review/pr-1907: 74 files
./pr-review/pr-1908: 74 files
./pr-review/pr-1909: 74 files
./pr-review/pr-1910: 74 files
./pr-review/pr-1911: 74 files
./pr-review/pr-1912: 74 files
./pr-review/pr-1913: 74 files
./pr-review/pr-1914: 74 files
./pr-review/pr-1915: 74 files
./pr-review/pr-1916: 74 files
./pr-review/pr-1917: 74 files
./pr-review/pr-1918: 74 files
./pr-review/pr-1919: 74 files
./pr-review/pr-1920: 74 files
./pr-review/pr-1921: 74 files
./pr-review/pr-1922: 74 files
./pr-review/pr-1923: 74 files
./pr-review/pr-1924: 74 files
./pr-review/pr-1925: 74 files
./pr-review/pr-1926: 74 files
./pr-review/pr-1927: 74 files
./pr-review/pr-1928: 74 files
./pr-review/pr-1929: 74 files
./pr-review/pr-1930: 74 files
./pr-review/pr-1931: 74 files
./pr-review/pr-1932: 74 files
```
</details>

<details>
<summary><h2>List of currently open PRs</h2></summary>

```
1932
1930
1921
1916
1914
1890
1869
1866
1826
1807
1801
1793
1790
1784
1779
1778
1776
1757
```
</details>

<details>
<summary><h2>Workflow File</h2></summary>
Our workflow is relatively straightforward. I kept this action untouched and stubbed out other, less important steps with self-explanatory names.

```
---
name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  REACT_APP_BASENAME: 'pr-preview/pr-${{ github.event.number }}'

jobs:
  deploy-pr-preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' }}
    steps:
      - uses: actions/checkout@v3
      - { name: "Install Python 3.9", uses: actions/setup-python@v4, with: { python-version: '3.9' } }
      - { name: "Install Node 16", uses: actions/setup-node@v3, with: { node-version: '16' } }

      - name: Create homepage var in package.json 
        run: echo $(jq --arg REACT_APP_BASENAME "$REACT_APP_BASENAME" ".homepage=\"/$REACT_APP_BASENAME\"" package.json) > package.json}

      - name: Setup internal actions helpers
      - name: Configure npm credentials

      - run: yarn --frozen-lockfile

      - name: Congfigure aws
      - name: GraphQL codegen

      - run: yarn build

      - name: Copy extra files into build directory

      - name: Upload Sentry Sourcemaps

      - name: Deploy PR for Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/

  close-pr-preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' }}
    steps:
      - uses: actions/checkout@v3
      - name: Close PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-previews
          action: auto

```
</details>

<details>
<summary><h2>Environment logs for deploy action</h2></summary>
I took the liberty of removing our environment variables for brevity

```
Run rossjrw/pr-preview-action@v1
  with:
    source-dir: ./build/
    token: ***
    preview-branch: gh-pages
    umbrella-dir: pr-preview
    deploy-repository: <redacted>
    action: auto
  env:
    YARN_INSTALL_ARGS: <redacted>
    REACT_APP_BASENAME: pr-preview/pr-1932
    pythonLocation: /opt/hostedtoolcache/Python/3.9.18/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib
    PATH: <redacted>
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
Run echo "action=$action" >> $GITHUB_ENV
Run action_version=$("$GITHUB_ACTION_PATH/lib/find-current-git-tag.sh" -p $actionrepo -f $actionref)
Determining Git tag for rossjrw/pr-preview-action/v1
Cloning repository rossjrw/pr-preview-action at ref v1
Cloning into bare repository 'bare_pr_preview'...
Run $GITHUB_ACTION_PATH/lib/determine-auto-action.sh
event_name is pull_request; proceeding
event_type is synchronize
Run JamesIves/github-pages-deploy-action@v4
  with:
    token: ***
    repository-name: <redacted>
    branch: gh-pages
    folder: ./build/
    target-folder: pr-preview/pr-1932
    commit-message: Deploy preview for PR 1932 🛫
    force: false
    clean: true
  env:
    YARN_INSTALL_ARGS: <redacted>
    REACT_APP_BASENAME: pr-preview/pr-1932
    pythonLocation: /opt/hostedtoolcache/Python/3.9.18/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib
    PATH: <redacted>
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
    action: deploy
    targetdir: pr-preview/pr-1932
    pr: 1932
    pagesurl: <redacted>
    emptydir: /tmp/tmp.emXPpMVUFU
    datetime: 2024-01-25 19:19 UTC
    actionref: v1
    actionrepo: rossjrw/pr-preview-action
    deployrepo: <redacted>
    token: ***
    action_version: v1.4.6
```
</details>
