### DISCUSSION TITLE
Run action on labeled, unlabeled

### DISCUSSION THREAD

**Discussion by sophie-warner-annalise-ai** [rossjrw/pr-preview-action#91] [Q&A] [answered]
Hey, what do you reckon about allowing the action to be triggered when a label gets added? I have a label that I'd like to change my env vars. 

## Current flow
1. Open PR
2. Action runs
3. User manually adds label 
4. Push another commit
5. Action runs with label based on env var

## Proposed flow 
1. Open PR
2. Action runs
3. User manually adds label
4. Action runs with label based on env var
5. Push another commit
6. Action runs with label based on env var

**Comment by rossjrw** [comment, marked as answer]
Moved to Discussion as this is a question about a setup issue rather than a problem with the action itself. (If a problem with the action is discovered as part of this discussion, please create an issue for that.)

This Action can be run on any event as defined by your workflow: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows

The PR event contains `labeled` and `unlabeled` activity types, so you could modify your event trigger to add those:

```yaml
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
      - labeled
      - unlabeled
```

However - if you use this Action with parameter `action: auto` (which is the default value), checks between activity types `opened`, `reopened`, `synchronize` and `closed` to determine whether the PR preview should be created or removed:

https://github.com/rossjrw/pr-preview-action/blob/430e3dfc1de8a8ae77e77d862d25676ef9db55d1/lib/determine-auto-action.sh#L17-L28

If the Action runs on events `pull_request.labeled` or `pull_request.unlabeled`, it therefore won't do anything by default, so you'll have to add that logic yourself. Off the top of my head, given that you can add/remove PR labels from closed PRs, that logic comes down to 'if the PR is open, make the preview; if the PR is closed, do nothing'. Your use case might be more nuanced.

You could do that with an `if:` condition in the workflow step for the preview that reads the PR state from the event (https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request), so your workflow might look something like this:

```yaml
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - previous steps in your workflow go here

      # If event is labeled/unlabeled, deploy preview if PR is open
      - uses: rossjrw/pr-preview-action@v1
        if: contains(fromJSON('["labeled", "unlabeled"]'), github.event.pull_request.action) && github.event.pull_request.state == 'open'
        with:
          action: deploy

      # Otherwise, let preview action decide whether to deploy/remove preview
      - uses: rossjrw/pr-preview-action@v1
        if: ${{ ! contains(fromJSON('["labeled", "unlabeled"]') }}
        with:
          action: auto
```

Haven't tested the above, but something like it might work for you.
