### ISSUE TITLE
`'main' is already used by worktree` error when closing a pull request

### ISSUE THREAD

**Issue by chetbox** [rossjrw/pr-preview-action#109]
Using this configuration I get an error every time a pull request is closed.

```yml
name: UI preview - PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

concurrency:
  group: ui-preview-pr-${{ github.event.pull_request.number }}

jobs:
  cogs_ui_preview:
    runs-on: ubuntu-24.04
    steps:
      ...
      - name: PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .ui-demo
          deploy-repository: clockwork-dog/cogs-ui-preview
          token: ${{ secrets.GH_PAT }}
          preview-branch: main
```

Note that the default branch on the source and the preview repos is `main` and `main` is the branch used to host GitHub Pages on the preview repo. Both repos are private.

Here's the error:

```
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config --global --add safe.directory /home/runner/work/cogs/cogs
/usr/bin/git config user.name chetbox
/usr/bin/git config user.email chetbox@users.noreply.github.com
/usr/bin/git config core.ignorecase false
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/clockwork-dog/cogs-ui-preview.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/clockwork-dog/cogs-ui-preview.git refs/heads/main
d2a37c90f3089548213ed2f88e671c7f7e5c1222	refs/heads/main
Creating worktree…
/usr/bin/git fetch --no-recurse-submodules --depth=1 origin main
From https://github.com/clockwork-dog/cogs-ui-preview
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD ae96c1c)
/usr/bin/git checkout -B main origin/main
fatal: 'main' is already used by worktree at '/home/runner/work/cogs/cogs'
```
