### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by rylegarcia** [rossjrw/pr-preview-action#13]
After following the [Usage](https://github.com/rossjrw/pr-preview-action#usage), I'm able to see deploy preview link in the PR. However, when I access the link, I get taken to a 404 page not found. 

In the screenshot below, it shows the `gh-pages` branch which contains my `index.html` file (ie: `pr-preview > pr-90 > index.html`). Am I missing a step?

<img width="1506" alt="Screen Shot 2022-08-17 at 5 15 39 PM" src="https://user-images.githubusercontent.com/10470129/185244498-49202439-d221-4c2a-9052-a3a150b671e3.png">

Below is my config. In the master branch, my index.html lives in `docs > index.html`

```
name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Install and Build
        run: |
          npm install
          npm run build
          npm run build-storybook

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/
```
