### ISSUE TITLE
Combine with `actions/deploy-pages`

### ISSUE THREAD

**Issue by astrojuanlu** [rossjrw/pr-preview-action#21]
This workflow seems to target the "classic" GitHub Pages experience. However, nowadays there's also the newer workflow using https://github.com/marketplace/actions/deploy-github-pages-site

![image](https://user-images.githubusercontent.com/316517/194744490-5f05d71a-48b9-4baa-9e4c-5e5435b29177.png)

I'm trying to combine the two actions but so far I've been unsuccessful: either nothing happens, or I'm getting errors coming from `actions/deploy-pages` saying `Branch "..." is not allowed to deploy to github-pages due to environment protection rules.`

Do you have an example on how to use `rossjrw/pr-preview-action` with the new workflow?

**Comment by rossjrw** [comment]
I'm afraid I don't currently have any examples - the above workflow is new to me! I'll make sure to assess whether the two can be reconciled at some point in the future - thanks for bringing it up.

**Comment by vincerubinetti** [comment]
I wonder if the new "Pages from Actions" option would even support something like this? Also, if people haven't seen this yet, [GitHub is supposedly working on integrating this feature directly into GitHub](https://github.com/community/community/discussions/7730). It'd be nice to not have to link Netlify to repos anymore!

**Comment by MattF-NSIDC** [comment]
>I wonder if the new "Pages from Actions" option would even support something like this?

I think it's much harder with the "Pages from Actions" workflow, and requires sacrificing atomicity. With "Pages from branch", you can add a subdirectory easily to the `gh-pages` branch. With "Pages from Actions", all deployments are atomic, like Netlify deploys, which is great. Until you want to do something like add a directory to a deployed site. That might look like:

* Download the currently-deployed site (how?);
* add a subdirectory to the local copy;
* push that new directory structure as a pages artifact;
* `actions/deploy-pages`.
 
But now when your next atomic production deploy comes through, the preview is overwritten! Not as simple as I first thought to work around this. So I went with Netlify.

I'm hoping the feature GitHub is working on enables both atomic preview deploys (like Netlify) and atomic production deploys that can't step on each-others' toes messing with adding subdirectories. e.g. previews deploy to `preview-pr-N.mysite.github.io` or something :shrug:

**Comment by rossjrw** [comment]
Noting that I've looked into this a little further, detailing some thoughts here: https://github.com/orgs/community/discussions/30113#discussioncomment-7650234

I'm not sure that the artifact-based deployment method has the versatility to support this action. @MattF-NSIDC raises some excellent points and I think I would have come to the same conclusions.

Looking at the 'preview' parameter of `actions/deploy-pages` that MattF linked, it looks like that parameter gets sent to the `/repos/{owner}/{repo}/pages/deployments` octokit endpoint as part of the payload. [Octokit docs](https://octokit.github.io/rest.js/v20#repos-create-deployment) state 'The payload parameter is available for any extra information that a deployment system might need'... so I actually have no idea where that parameter ends up being used or what it does.

It sounds like the `actions/deploy-pages` maintainers don't have a timeline for it either (https://github.com/actions/deploy-pages/issues/180) so I'm not particularly hopeful. If it does end up working how MattF hypothesises I'll probably jump ship to it straight away, but I'm not going to dwell on it in the meantime.

> But now when your next atomic production deploy comes through, the preview is overwritten! Not as simple as I first thought to work around this.

Ironically the ideal solution to this IMO would be something Git-based... maybe the deployment artifact could be a Git repository? Maybe streamline that to be a branch of the current repository? What if you could deploy Pages directly from a branch? 😛

**Comment by rickstaa** [comment]
I attempted to tackle the issue of deploying a GitHub Pages PR preview through a specific GitHub Action workflow. Despite following the setup steps correctly and verifying that the files are appropriately placed on the `gh-pages/pr-preview/pr-6` branch, the site fails to render when accessing the generated preview URL.

### Workflow Configuration

Below is the YAML configuration for the GitHub Action I have used:

```yml
name: Deploy GitHub pages PR preview

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "preview-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./_site

  preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./_site
      - uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.FORK_TOKEN }}
          source-dir: ./_site
          custom-url: livepeer.cool
```

### Issue Description

The workflow is intended to build and deploy a preview of GitHub Pages for pull requests targeting the `main` branch. I attempted to use the `actions/upload-pages-artifact` and `actions/upload-artifact` actions to upload the build artifacts. The artifacts seem to be correctly located in the `gh-pages/pr-preview/pr-6` branch, as verified by the following resources:
- Action Run: [https://github.com/rickstaa/awesome-livepeer/actions/runs/7739787858/job/21103378169](https://github.com/rickstaa/awesome-livepeer/actions/runs/7739787858/job/21103378169)
- Pull Request: [https://github.com/rickstaa/awesome-livepeer/pull/6](https://github.com/rickstaa/awesome-livepeer/pull/6)

Despite the successful placement of files, accessing the generated preview URL does not render the site as expected.

### Request for Assistance

Maybe this is not yet possible with the https://github.com/rossjrw/pr-preview-action/ action as the comments above suggest, but could anyone provide insights or suggestions on why the GitHub Pages site is not rendering from the PR preview despite the successful artifact upload and branch placement? Any guidance on troubleshooting this issue or adjustments to the GitHub Action workflow would be greatly appreciated 🙏🏻.
