### ISSUE TITLE
Customize the directory to serve from

### ISSUE THREAD

**Issue by Tbhesswebber** [rossjrw/pr-preview-action#42]
Our Github Pages configuration is set up to serve from a subdirectory and there is currently no documented way to address this with pr-preview-action.

## Example:

**Preview Deployment Action**

```yaml
      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs
          preview-branch: gh-pages
          umbrella-dir: docs/pr-preview
          action: auto
```

**Deployment Action**

```yaml

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          target-folder: docs
          branch: gh-pages
          clean-exclude: docs/pr-preview
```

With the above configurations, we end up with everything correctly being saved to the `docs` directory.  The generated preview link is `/docs/pr-preview/pr-xx`.  I can delete the `/docs` path part and see the preview just fine, but the generated link shows a totally valid 404 because we are serving directly from the `docs` directory that things are being saved to rather than serving from the root directory.

**Comment by rossjrw** [comment]
Deploying documentation to `docs/` on the main branch vs deploying it to the root directory on the `gh-pages` branch are typically two _different_ methods of isolating GitHub Pages deployments from the rest of the codebase. I'd say it's unusual to see a deployment to the `docs/` directory on the `gh-pages` branch - is this setup definitely intended?

A more traditional approach would be to copy `docs/` on your feature branch to the root of the `gh-pages` branch:

```yml
# Preview
      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
```

```yml
# Main deployment
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          target-folder: .
          branch: gh-pages
          clean-exclude: pr-preview
```

That would probably be easiest and more in line with the 'standard' approach.

But assumptions and principle aside, if you really do need to deploy from `docs/` on `gh-pages` and you're using the root dir on `gh-pages` for something else, then you're right - there's currently no way to do that. The variable used for the deployment target dir is the same as the one used to construct the URL:

https://github.com/rossjrw/pr-preview-action/blob/022361539c71c58a7141d4fe8c3e0e4a1c34f9c5/action.yml#L131

https://github.com/rossjrw/pr-preview-action/blob/022361539c71c58a7141d4fe8c3e0e4a1c34f9c5/action.yml#L152-L153

The long-term solution to this would be to add a parameter that indicates what directory Pages is being served from in that repo, as you originally suggested.
