### ISSUE TITLE
How can I load gh-pages/pr-preview file?

### ISSUE THREAD

**Issue by seongminn** [rossjrw/pr-preview-action#46]
this is my workflows file.
```yaml
name: Create Preview Site
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  pages: write
  deployments: write

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: yarn install && yarn build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
          preview-branch: gh-pages
          umbrella-dir: pr-preview/
          action: auto
```

and this is my `pr-preview/pr-22/assets/` on `gh-pages` branch.

![image](https://user-images.githubusercontent.com/88662637/235345306-9bf63446-adcf-4213-a426-5f80f0e0aa78.png)

But I can not access my `index-dd097f21.js` file on my deployed site for preview.

![image](https://user-images.githubusercontent.com/88662637/235345382-340725c0-fc11-4bee-9b6c-46ba9418628a.png)

How can I access `pr-preview` directory on `gh-pages` branch?
