### ISSUE TITLE
Add ability to specify GitHub pages directory

### ISSUE THREAD

**Issue by RedSparr0w** [rossjrw/pr-preview-action#80]
Currently as far as I can tell, you are not able to specify the directory you are using to serve your GitHub pages project.
This means when the preview URL is generated it still includes the pages directory pointing to a broken link.

For example, my repo uses `docs/` as the GitHub pages base directory, with the following config I get this output:
```yml
          source-dir: 'build'
          preview-branch: 'master'
          umbrella-dir: 'docs/preview'
          custom-url: 'example.site'
```
Output URL: `https://example.site/docs/preview/pr-123`
Expected URL: `https://example.site/preview/pr-123`
