### ISSUE TITLE
Possible to support multiple comments on a PR?

### ISSUE THREAD

**Issue by luke-denton-ofx** [rossjrw/pr-preview-action#96]
The sticky-pull-request-comment action supports multiple comments on a single PR through the use of the `header` property.

Is it possible to expose that functionality through pr-preview-action?

**Comment by rossjrw** [comment]
The action sets `header` to a hardcoded value of `pr-preview`, so presumably it is not affecting unrelated sticky comments on the same PR (I hope!)

Could you share a use case for this?

**Comment by luke-denton-ofx** [comment]
Absolutely. So I'm keen to deploy two things on each PR. Our SPA, and a Storybook instance for the code that has been changed. The reason for this is we're currently in the process of creating a new design system, so for the short term, we very likely will only have Storybook stories to review individual components.

Your action works perfectly to achieve that, the only thing that we miss out on is having both environments linked to in a comment.

This is our action that is making use of your action, and it would be great if we could pass through a custom `header` value, with the default being `pr-preview`. In the code below, I've got storybook listed first, so that its comment gets overwritten by the app preview comment, as the preview action that runs last is the one whose comment wins (bit of a mouth full 🫠).
In this context, `header` probably doesn't make the most sense, so I'd be more than happy for you to come up with a naming convention that does make sense

```
deploy-preview:
    # ...
      - name: Deploy Storybook preview
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          header: storybook-preview # desired custom value here
          source-dir: ./storybook/storybook-static/
          umbrella-dir: storybook-preview
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: ./build/
```

While it would be great to be able to pass options down to the underlying actions that pr-preview-actions is using, even if that's as an undocumented feature for people who "know what they're doing", in the short term, being able to control how many comments are added to a PR would be amazing

**Comment by rossjrw** [comment]
The default comment can now be disabled as of [v1.6.0](https://github.com/rossjrw/pr-preview-action/releases/tag/v1.6.0) and new output parameters can be used to construct your own comment using whatever marketplace action you like.

This isn't exactly what you were asking for, but it's more flexible - you could disable the default comment for both previews and use e.g. https://github.com/marocchino/sticky-pull-request-comment (or whatever action or homebrew script you like) to add a comment for each.

If you wanted to reproduce [the default comment as of v1.6.0](https://github.com/rossjrw/pr-preview-action/blob/df22037db54ab6ee34d3c1e2b8810ac040a530c6/action.yml#L139):

```yml
    - uses: rossjrw/pr-preview-action@v1
      id: preview-step
      with:
        comment: false

    - uses: marocchino/sticky-pull-request-comment@v2.9.0
      if: env.deployment_action == 'deploy' && env.deployment_status == 'success'
      with:
        header: pr-preview
        message: |
          [PR Preview Action](https://github.com/rossjrw/pr-preview-action) ${{ steps.preview-step.outputs.action-version }}
          :---:
          | <p></p> :rocket: View preview at <br> ${{ steps.preview-step.outputs.preview-url }} <br><br>
          | <h6>Built to branch [`BRANCH_NAME_HERE`](${{ github.server_url }}/${{ github.repository }}/tree/BRANCH_NAME_HERE) at ${{ steps.preview-step.outputs.action-start-time }}. <br> Preview will be ready when the [GitHub Pages deployment](${{ github.server_url }}/${{ github.repository }}/deployments) is complete. <br><br> </h6>
```
